### PR TITLE
fix: SfGallery - set initial slide

### LINKED ISSUE #663: [BUG] SfGallery - set initial slide
**Describe the bug**
When I want to set initial slide as second one `:current="2"` I have active second thumb and image from first slide.

**How to reproduce**
1. Create gallery with minimum 2 slides.
2. set initial slide `:current="2"`

**Expected behavior**
If I set `:current="2"` I will have **second** thumb and image from **second** slide.

**Actual behavior**
If I set `:current="2"` I have **second** thumb and image from **first** slide.

*Additional context**
I resolved this issue by passing 
```
      :current="2"
      :slider-options="{startAt: 1}"
```
`current` is needed to have second thumb (`this.activeIndex` in SfGallery)
`slider-options` set second slide in Glide

Maybe remove `current` prop and use only `sliderOptions`? Or pass value from `current` to Glide options (`const glide = new Glide(this.$refs.glide, {...this.sliderOptions, startAt: this.activeIndex});`)?

### PR DESCRIPTION
**Pull request by aniamusial**
# Related issue
Closes #663 

# Scope of work
- added computed property setting activeIndex for glidejs `startAt` option

# Checklist

- [x] No commented blocks of code left
- [x] Run tests and docs
- [x] Self code-reviewed

### CODE REVIEW

File: packages/vue/src/components/molecules/SfGallery/SfGallery.vue [hunk 1]
```diff
@@ -147,14 +147,21 @@ export default {
         mobile: desktop,
         desktop: big
       }));
+    },
+    updatedSliderOptions() {
+      if (this.current === 0) {
+        return this.sliderOptions;
+      } else {
+        return { ...this.sliderOptions, startAt: this.activeIndex };
```
Comment (pspaczek) [inline packages/vue/src/components/molecules/SfGallery/SfGallery.vue]: @aniamusial we can always use else function
