### PR TITLE
fix: SfAddressPicker doesn't react to "selected" prop changes

### LINKED ISSUE #1490: [BUG] SfAddressPicker doesn't react to "selected" prop changes
**Describe the bug**
When `SfAddressPicker` component is created, it copies the value of `selected` prop to internal variable `checked`. However, if I  change value of `selected` lated, it doesn't reflect the change.

**Expected behavior**
When `selected` prop is changed, component should override `checked` property with new value.

**Actual behavior**
Component ignores changes of `selected` prop.

### PR DESCRIPTION
**Pull request by justyna-13**
# Related issue
Closes #1490 #1491

# Scope of work
Changed prop name, added watch and emitted event 

# Screenshots of visual changes
No visual changes 

# Checklist

- [ ] No commented blocks of code left
- [ ] Run tests and docs
- [ ] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/contributing/coding-guidelines.html#component-rules) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

File: packages/vue/src/components/molecules/SfAddressPicker/SfAddressPicker.vue [hunk 1]
```diff
@@ -1,5 +1,5 @@
 <template>
-  <div class="sf-address-picker">
+  <div class="sf-address-picker" @change="inputHandler">
```
Comment (Fifciu) [inline packages/vue/src/components/molecules/SfAddressPicker/SfAddressPicker.vue:2]: inputHandler will never be called

File: packages/vue/src/components/molecules/SfAddressPicker/SfAddressPicker.vue [hunk 2]
```diff
@@ -12,14 +12,14 @@ Vue.component("SfAddress", SfAddress);
 export default {
   name: "SfAddressPicker",
   props: {
-    selected: {
+    value: {
```
Comment (Fifciu) [inline packages/vue/src/components/molecules/SfAddressPicker/SfAddressPicker.vue:15]: Sounds like a breaking change (or maybe earlier it was like that?) - if not, you could use https://vuejs.org/v2/api/#model

File: packages/vue/src/components/molecules/SfAddressPicker/SfAddressPicker.vue [hunk 3]
```diff
@@ -28,13 +28,21 @@ export default {
       setSelectedValue: this.setSelectedValue,
     };
   },
+  watch: {
+    value(newVal) {
```
Comment (Fifciu) [inline packages/vue/src/components/molecules/SfAddressPicker/SfAddressPicker.vue:32]: Remember to change it to `selected` if you could restore this props name

File: packages/vue/src/components/molecules/SfAddressPicker/SfAddressPicker.vue [hunk 4]
```diff
@@ -28,13 +28,21 @@ export default {
...
     getSelectedValue() {
-      return this.checked;
+      return this.selectedValue;
     },
     setSelectedValue(newVal) {
       const newValue = newVal;
-      this.checked = newValue;
+      this.selectedValue = newValue;
+    },
+    inputHandler() {
```
Comment (Fifciu) [inline packages/vue/src/components/molecules/SfAddressPicker/SfAddressPicker.vue:44]: I think instead of creating this function you could emit this event in setSelectedValue as you are providing it to the childs

**Review by Fifciu — CHANGES_REQUESTED** [review]

**Review by Fifciu — APPROVED** [review]

**Review by AdamPawlinski — APPROVED** [review]
Great, perfectly done :+1:
