### PR TITLE
fix: add role attribute to sfTab to signify a button

### LINKED ISSUE #746: [BUG] SfTab should be a button
**Describe the bug**
Currently SfTab is a clickable` <div>` - it should be a styled `<button>` for accessability reasons.

### PR DESCRIPTION
**Pull request by peoray**
# Related issue

Fixes #746

# Scope of work
Added an attribute of `role="button"` to enable the div identify as a button using screen readers

# Checklist

- [ ] No commented blocks of code left
- [ ] Run tests and docs
- [ ] Self code-reviewed

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/contributing/coding-guidelines.html#component-rules) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

File: packages/vue/src/components/organisms/SfTabs/_internal/SfTab.vue [hunk 1]
```diff
@@ -3,6 +3,7 @@
     <!--@slot Title. Here you should pass a title tab-->
     <slot name="title" v-bind="{ tabClick, isActive, title }">
       <div
+        role="button"
```
Comment (pspaczek) [inline packages/vue/src/components/organisms/SfTabs/_internal/SfTab.vue]: @peoray if you can add one small improvement that would be great
```suggestion
        role="button"
        :aria-pressed="isActive.toString()"
```

**Comment by pspaczek** [comment]
@peoray thank you 💚
