### PR TITLE
fix: type for SfButton in SfModal

### LINKED ISSUE #1378: [BUG] SfModal close button 's type is submit (default html), it submits forms on close if placed within one.
**Describe the bug**
Placing SfModal inside a <form> will submit the form when cross (SfButton) is clicked.

**How to reproduce**
1. Mount SfModal inse a html form 
2. click on close cross in the modal
3. observe form being submitted

**Expected behavior**
Modal close button type is set to `button` so it doesnt act as a submit trigger

**Actual behavior**
it does submit.

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.
```
//Write code here
```
Or add code snippets (Code sandbox)

**Screenshots**

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

### PR DESCRIPTION
**Pull request by justyna-13**
# Related issue
Closes #1378 

# Scope of work
Type for SfButton added

# Screenshots of visual changes
No visual changes

# Checklist

- [ ] No commented blocks of code left
- [ ] Run tests and docs
- [ ] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/contributing/coding-guidelines.html#component-rules) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

File: packages/vue/src/components/atoms/SfButton/SfButton.vue [hunk 1]
```diff
@@ -5,6 +5,7 @@
     class="sf-button"
     v-bind="$attrs"
     :disabled="disabled"
+    :type="isButton"
```
Comment (mayashavin) [inline packages/vue/src/components/atoms/SfButton/SfButton.vue:8]: I don't think we need this additional prop - `type` is one of the built-in HTML element attribute for `button`, so may just use `$attrs` to see if any `type` passed. WDYT?

Comment (justyna-13) [reply packages/vue/src/components/atoms/SfButton/SfButton.vue:8]: you're right, I'll add type only for button in modal :)

**Review by mayashavin — APPROVED** [review]
