### PR TITLE
fix: SfPagination pass link as string

### LINKED ISSUE #1424: [BUG] SfPagination error on SSR
**Describe the bug**
When on nuxt Storybook, clicking on page number leads to showing the error in console.

**How to reproduce**
Run project on nuxt with Storybook, open SfPagination component and click on the page number. 
Then you will see the error regarding 'to' prop in the console.

**Expected behavior**
No error and change the active page when clicking on that page.

**Screenshots**
image

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

### PR DESCRIPTION
**Pull request by justyna-13**
# Related issue
Closes #1424 

# Scope of work
Invalid prop type changed on string

# Screenshots of visual changes
No visual changes

# Checklist

- [ ] No commented blocks of code left
- [ ] Run tests and docs
- [ ] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/contributing/coding-guidelines.html#component-rules) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

File: packages/vue/src/components/molecules/SfPagination/SfPagination.vue [hunk 1]
```diff
@@ -202,10 +202,9 @@ export default {
       this.$emit("click", page);
     },
     getLinkTo(page) {
-      return {
-        ...this.$route,
-        query: { ...this.$route.query, [this.pageParamName]: page },
-      };
+      Object.assign(this.$route.query, { [this.pageParamName]: page });
```
Comment (mayashavin) [inline packages/vue/src/components/molecules/SfPagination/SfPagination.vue:205]: Do we want to modify `this.$route.query` or we just want to get the link to page from Object to string?

If we just want to get the link to page, we don't need this line.
If we do, we need to make sure there is no effect when we change `$route.query`
@justyna-13 please check

**Review by mayashavin — CHANGES_REQUESTED** [review]
See my comment

File: packages/vue/src/components/molecules/SfPagination/SfPagination.vue (hunk 1 above)
Comment (justyna-13) [reply packages/vue/src/components/molecules/SfPagination/SfPagination.vue:205]: right, we don't need to modify it, works without it :)

**Review by AdamPawlinski — APPROVED** [review]
