### PR TITLE
a11y: button tags instead of role="button" in clickable SfIcon + molecules with v-focus

### LINKED ISSUE #1084: [REFACTOR] [a11y] Change `role="button"` elements to native <button>
**Describe the bug**
SfIcon in many cases acts as a button and has `role="button"` 
**Expected behavior**
Elements which are clickable should be native elements `<button>`

### PR DESCRIPTION
**Pull request by justyna-13**
# Related issue
Closes #1084 

# Scope of work
role="button" in SfIcon changed on button tags
SfCircleIcon is a button so no need to add role="button"

### CODE REVIEW

File: packages/vue/src/components/molecules/SfBar/SfBar.vue [hunk 1]
```diff
@@ -1,38 +1,38 @@
...
-        <SfIcon
-          v-if="back"
-          icon="chevron_left"
-          size="14px"
-          role="button"
-          aria-label="back"
-          @click="$emit('click:back')"
-        />
-      </div>
+        <button v-focus class="sf-bar__icon">
```
Comment (martaradziszewska) [inline packages/vue/src/components/molecules/SfBar/SfBar.vue:4]: maybe we can use `SfButton` here, wdyt? @justyna-13

File: packages/shared/styles/components/molecules/SfNotification.scss [hunk 2]
```diff
@@ -60,6 +60,8 @@
     top: var(--notification-close-top, var(--spacer-xs));
     right: var(--notification-close-right, var(--spacer-xs));
     cursor: pointer;
+    background: transparent;
```
Comment (martaradziszewska) [inline packages/shared/styles/components/molecules/SfNotification.scss:63]: maybe we should add some modifier to button ? like `--icon` - now we have many repeated properties to remove properties, wdyt @justyna-13 @pspaczek  ?

File: packages/vue/src/components/molecules/SfBar/SfBar.vue [hunk 3]
```diff
@@ -1,38 +1,38 @@
...
-          icon="cross"
-          size="14px"
-          role="button"
-          aria-label="close"
-          @click="$emit('click:close')"
-        />
-      </div>
+        <button v-focus class="sf-bar__icon">
+          <SfIcon
+            v-if="close"
```
Comment (martaradziszewska) [inline packages/vue/src/components/molecules/SfBar/SfBar.vue:20]: `v-if` should be on button, the same as `aria-label` and click method. Please check other icons :)

File: packages/vue/src/components/molecules/SfBar/SfBar.vue [hunk 4]
```diff
@@ -1,38 +1,38 @@
...
+            aria-label="close"
+            @click="$emit('click:close')"
+          />
+        </button>
     </slot>
   </div>
 </template>
 <script>
 import SfIcon from "../../atoms/SfIcon/SfIcon.vue";
+import { focus } from "../../../utilities/directives/focus-directive.js";
```
Comment (martaradziszewska) [inline packages/vue/src/components/molecules/SfBar/SfBar.vue:32]: if we use SfButton, we don't have to import focus :)

File: packages/vue/src/components/organisms/SfCollectedProduct/SfCollectedProduct.vue [hunk 5]
```diff
@@ -13,11 +13,9 @@
       >
     </slot>
     <slot name="more-actions">
-      <SfIcon
-        icon="more"
-        role="button"
-        class="sf-collected-product__more-actions mobile-only"
-      />
+      <button class="sf-collected-product__more-actions mobile-only">
```
Comment (martaradziszewska) [inline packages/vue/src/components/organisms/SfCollectedProduct/SfCollectedProduct.vue:16]: this button should have descriptive aria-label because there is no text inside. Please check other elements

File: packages/shared/styles/components/molecules/SfNotification.scss (hunk 2 above)
Comment (justyna-13) [reply packages/shared/styles/components/molecules/SfNotification.scss:63]: Sounds good for me :) we have some places where we change the same properties for button with icons

File: packages/vue/src/components/molecules/SfBar/SfBar.vue (hunk 1 above)
Comment (justyna-13) [reply packages/vue/src/components/molecules/SfBar/SfBar.vue]: If @pspaczek agrees on the new modifier to button then it'll be better with SfButton here but if not, then I'd rather stay with button tag - will be less changes to do :)

File: packages/shared/styles/components/molecules/SfNotification.scss (hunk 2 above)
Comment (pspaczek) [reply packages/shared/styles/components/molecules/SfNotification.scss:63]: button--unstyled? Then you can use it for all case, not only for icon. @martaradziszewska, @justyna-13?

Comment (pspaczek) [reply packages/shared/styles/components/molecules/SfNotification.scss:63]: button--unstyled === reset button styles

Comment (pspaczek) [reply packages/shared/styles/components/molecules/SfNotification.scss:63]: https://github.com/DivanteLtd/storefront-ui/issues/1116 issues

**Comment by pspaczek** [comment]
@justyna-13 thank you, here you can find issues for improve this PR https://github.com/DivanteLtd/storefront-ui/issues/1116
