### PR TITLE
fix: shadow for carousel items

### LINKED ISSUE #999: [BUG] 0.7.0 shadow on carousel
**Describe the bug**
Product Card box-shadows and Carousel on Home example should be fixed

**Screenshots**
Zrzut ekranu 2020-04-7 o 13 27 46
Zrzut ekranu 2020-04-7 o 13 27 51

### PR DESCRIPTION
**Pull request by justyna-13**
# Related issue
Closes #999 

# Scope of work
Visible shadow on carousel elements

### CODE REVIEW

**Comment by pspaczek** [comment]
@justyna-13 nice 🎖️ I think, we shouldn't use padding :( , these elements must be close to each other. The second thing. Like you see on the bottom screen it looks better but not enough. 
Zrzut ekranu 2020-04-15 o 16 05 04

File: packages/vue/src/examples/pages/home/Home.vue [hunk 1]
```diff
@@ -118,6 +118,9 @@ export default {
   },
   data() {
     return {
+      carouselSettings: {
```
Comment (pspaczek) [inline packages/vue/src/examples/pages/home/Home.vue:121]: @justyna-13 we should use it just for desktop width

File: packages/vue/src/examples/pages/home/Home.vue [hunk 2]
```diff
@@ -331,7 +334,9 @@ export default {
   @include for-desktop {
     margin: 0;
   }
-  // todo: fix product shadow on carousel
+  &__item {
+    margin: var(--spacer-base) 0;
```
Comment (pspaczek) [inline packages/vue/src/examples/pages/home/Home.vue:338]:
```suggestion
    margin: 31px 0 39px 0; // convert px to rem 
```
because: you have 35px shadow with offset-y=4px

File: packages/vue/src/examples/pages/home/Home.vue [hunk 3]
```diff
@@ -32,7 +32,10 @@
       image="/assets/storybook/Home/newsletter.jpg"
     />
     <SfSection title-heading="Bestsellers">
-      <SfCarousel class="carousel">
+      <SfCarousel 
+        :settings="isMobile ? { peek: 0 } : { peek: 16 }"
```
Comment (pspaczek) [inline packages/vue/src/examples/pages/home/Home.vue:36]: @justyna-13 maybe https://glidejs.com/docs/options/#breakpoints be better than isMobile

Comment (justyna-13) [reply packages/vue/src/examples/pages/home/Home.vue]: breakpoints added and also perView option. Now, on mobile it looks similarly to the design on figma. Wdyt, @pspaczek ? :)

**Comment by pspaczek** [comment]
@justyna-13 thank you, look's good to me
