### PR TITLE
fix: SfProductCard isAddedToCart prop not changing icon

### LINKED ISSUE #1427: [BUG] SfProductCard isAddedToCart prop not changing icon
**Describe the bug**
On SfProductCard when prop isAddedToCart is true nothing changes in layout.

When isAddedToCart is false:
image

When isAddedToCart is true:
image

**How to reproduce**
Go to SfProductCard turn on isAddedToCart prop and see nothing changes on hover.  

**Expected behavior**
When isAddedToCart is on the icon should change to added_to_cart.

**Screenshots**

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

### PR DESCRIPTION
**Pull request by justyna-13**
# Related issue
Closes #1427 

# Scope of work

# Screenshots of visual changes
NO visual changes 

# Checklist

- [ ] No commented blocks of code left
- [ ] Run tests and docs
- [ ] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/contributing/coding-guidelines.html#component-rules) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

File: packages/vue/src/components/organisms/SfProductCard/SfProductCard.vue [hunk 1]
```diff
@@ -68,15 +68,21 @@
...
                   <SfIcon
                     key="add_to_cart"
                     icon="add_to_cart"
                     size="20px"
                     color="white"
                   />
                 </slot>
-                <slot v-else name="adding-to-cart-icon">
+                <slot
+                  v-if="isAddingToCart || isAddedToCart"
```
Comment (mayashavin) [inline packages/vue/src/components/organisms/SfProductCard/SfProductCard.vue:83]: put this one before the other `slot` and set the other slot condition to `v-else` instead of repeating the condition just in the opposite condition

**Review by mayashavin — CHANGES_REQUESTED** [review]
See my comment

File: packages/vue/src/components/organisms/SfProductCard/SfProductCard.vue (hunk 1 above)
Comment (mayashavin) [reply packages/vue/src/components/organisms/SfProductCard/SfProductCard.vue:83]: Something similar to 
```
<slot
    v-if="isAddingToCart || isAddedToCart"
    name="adding-to-cart-icon"
>
</slot>
<slot v-else
 name="add-to-cart-icon
>
</slot>
```
You don't need two `v-if`

**Review by AdamPawlinski — APPROVED** [review]
Perefectly :+1:
